import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/HomePage/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "@/components/HomePage/Footer";
import StoreProvider from "../../storeProvider/storeProvider";
import { Toaster } from "@/components/ui/toaster"



export const metadata: Metadata = {
  title: "PrimePick",
  description: "Generated by Anousha Asadullah",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
    <ClerkProvider>
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <Navbar/>
        {children}
        <Toaster/>
        <Footer/>
      </body>
    </html>
    </ClerkProvider>
    </StoreProvider>
  );
}
